/*CRIANDO O BANCO DE DADOS*/
CREATE DATABASE PROJETOBD1
/*USANDO O BANCO DE DADOS*/
USE PROJETOBD1
/*CRIANDO AS TABELAS DO BANCO DE DADOS*/
CREATE TABLE FUNCIONARIO(

COD_FUNC INT PRIMARY KEY IDENTITY,
NOME_FUNC VARCHAR(50)
)
CREATE TABLE CLIENTE(
COD_CLI INT PRIMARY KEY IDENTITY,
NOME_CLI VARCHAR(50),
)
CREATE TABLE PRODUTO(
COD_PROD INT PRIMARY KEY IDENTITY,
NOME_PROD VARCHAR(50),
QUANT_PROD INT
)
CREATE TABLE PEDIDO(
COD_PED INT PRIMARY KEY IDENTITY,
DESC_PED VARCHAR(50),
VALOR_PED FLOAT,
FK_COD_PROD INT,
FK_COD_CLI INT
FOREIGN KEY(FK_COD_PROD) REFERENCES PRODUTO(COD_PROD),
FOREIGN KEY(FK_COD_CLI) REFERENCES CLIENTE(COD_CLI),
)

CREATE TABLE VENDA(
COD_VEN INT PRIMARY KEY IDENTITY,
DESC_VEN VARCHAR(50),
FORMA_VEN VARCHAR(20),
FK_COD_PED INT,
FOREIGN KEY(FK_COD_PED) REFERENCES PEDIDO(COD_PED)
)
/*CONSULTADO AS TABELAS DO BANCO DE DADOS*/
SELECT * FROM FUNCIONARIO
SELECT * FROM CLIENTE
SELECT * FROM PRODUTO
SELECT * FROM PEDIDO
SELECT * FROM VENDA

/*INSERINDO INFORMAÇÕES NAS TABELAS*/

INSERT INTO FUNCIONARIO(NOME_FUNC) VALUES('COVIDELSON')
INSERT INTO FUNCIONARIO(NOME_FUNC) VALUES('COVICLEIDE')
INSERT INTO FUNCIONARIO(NOME_FUNC) VALUES('COVIFAT')


INSERT INTO CLIENTE(NOME_CLI,EMAIL)VALUES('CARECAOVALDO','CARECA@GMAIL.COM')
INSERT INTO CLIENTE(NOME_CLI,EMAIL)VALUES('ALTERALDO','ALTER@GMAIL.COM')
INSERT INTO CLIENTE(NOME_CLI,EMAIL)VALUES('DELETALDO','DELETE@GMAIL.COM')
INSERT INTO CLIENTE(NOME_CLI,EMAIL)VALUES('CONSULTALDO','CONSULTA@GMAIL.COM')

INSERT INTO PRODUTO(NOME_PROD,QUANT_PROD)VALUES('COLAR',10)
INSERT INTO PRODUTO(NOME_PROD,QUANT_PROD)VALUES('ESMALTE',20)
INSERT INTO PRODUTO(NOME_PROD,QUANT_PROD)VALUES('ANEL',15)
INSERT INTO PRODUTO(NOME_PROD,QUANT_PROD)VALUES('PORTA TRECO',16)

INSERT INTO PEDIDO(DESC_PED,VALOR_PED,FK_COD_PROD,FK_COD_CLI)
VALUES('COLLAR DIAMANTE NEGRITUDE',1200.00,1,1)

INSERT INTO PEDIDO(DESC_PED,VALOR_PED,FK_COD_PROD,FK_COD_CLI)
VALUES('ESMALTE',5.00,2,3)

INSERT INTO PEDIDO(DESC_PED,VALOR_PED,FK_COD_PROD,FK_COD_CLI)
VALUES('PORTA TRECO',40.00,3,3)

INSERT INTO PEDIDO(DESC_PED,VALOR_PED,FK_COD_PROD,FK_COD_CLI)
VALUES('ANEL',150.00,4,1)

INSERT INTO VENDA(DESC_VEN,FORMA_VEN,FK_COD_PED)
VALUES('COLLAR','DINHEIRO',2)

INSERT INTO VENDA(DESC_VEN,FORMA_VEN,FK_COD_PED)
VALUES('ANEL','CARTAO',2)

INSERT INTO VENDA(DESC_VEN,FORMA_VEN,FK_COD_PED)
VALUES('PORTA TRECO','DINHEIRO',2)

