/*CRIANDO O BANCO DE DADOS*/
CREATE DATABASE PROJETOBD1
/*USANDO O BANCO DE DADOS*/
USE PROJETOBD1
/*CRIANDO AS TABELAS DO BANCO DE DADOS*/
CREATE TABLE FUNCIONARIO(

COD_FUNC INT PRIMARY KEY IDENTITY,
NOME_FUNC VARCHAR(50)
)
CREATE TABLE CLIENTE(
COD_CLI INT PRIMARY KEY IDENTITY,
NOME_CLI VARCHAR(50),
)
CREATE TABLE PRODUTO(
COD_PROD INT PRIMARY KEY IDENTITY,
NOME_PROD VARCHAR(50),
QUANT_PROD INT
)
CREATE TABLE PEDIDO(
COD_PED INT PRIMARY KEY IDENTITY,
DESC_PED VARCHAR(50),
VALOR_PED FLOAT,
FK_COD_PROD INT,
FK_COD_CLI INT
FOREIGN KEY(FK_COD_PROD) REFERENCES PRODUTO(COD_PROD),
FOREIGN KEY(FK_COD_CLI) REFERENCES CLIENTE(COD_CLI),
)

CREATE TABLE VENDA(
COD_VEN INT PRIMARY KEY IDENTITY,
DESC_VEN VARCHAR(50),
FORMA_VEN VARCHAR(20),
FK_COD_PED INT,
FOREIGN KEY(FK_COD_PED) REFERENCES PEDIDO(COD_PED)
)
/*CONSULTADO AS TABELAS DO BANCO DE DADOS*/
SELECT * FROM FUNCIONARIO
SELECT * FROM CLIENTE
SELECT * FROM PRODUTO
SELECT * FROM PEDIDO
SELECT * FROM VENDA

